# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Api.ClientConfiguration do
  @moduledoc """
  API calls for all endpoints tagged `ClientConfiguration`.
  """

  alias FinAPIAccess.Connection
  import FinAPIAccess.RequestBuilder


  @doc """
  Edit client configuration
  Edit your client&#39;s configuration. Must pass your global (i.e. client) access_token.&lt;br/&gt;&lt;br/&gt; &lt;b&gt;NOTE&lt;/b&gt;: When token validity periods are changed, this only applies to newly requested tokens, and does not change the expiration time of already existing tokens.

  ## Parameters

  - connection (FinAPIAccess.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :body (ClientConfigurationParams): Client configuration parameters

  ## Returns

  {:ok, %FinAPIAccess.Model.ClientConfiguration{}} on success
  {:error, info} on failure
  """
  @spec edit_client_configuration(Tesla.Env.client, keyword()) :: {:ok, FinAPIAccess.Model.ClientConfiguration.t} | {:error, Tesla.Env.t}
  def edit_client_configuration(connection, opts \\ []) do
    optional_params = %{
      :"body" => :body
    }
    %{}
    |> method(:patch)
    |> url("/api/v1/clientConfiguration")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%FinAPIAccess.Model.ClientConfiguration{})
  end

  @doc """
  Get client configuration
  Get your client&#39;s configuration. Must pass your global (i.e. client) access_token.

  ## Parameters

  - connection (FinAPIAccess.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %FinAPIAccess.Model.ClientConfiguration{}} on success
  {:error, info} on failure
  """
  @spec get_client_configuration(Tesla.Env.client, keyword()) :: {:ok, FinAPIAccess.Model.ClientConfiguration.t} | {:error, Tesla.Env.t}
  def get_client_configuration(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/api/v1/clientConfiguration")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%FinAPIAccess.Model.ClientConfiguration{})
  end
end
