# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Api.WebForms do
  @moduledoc """
  API calls for all endpoints tagged `WebForms`.
  """

  alias FinAPIAccess.Connection
  import FinAPIAccess.RequestBuilder


  @doc """
  Get a web form
  Get a web form of the user that is authorized by the access_token. Must pass the web form&#39;s identifier and the user&#39;s access_token. &lt;br/&gt;&lt;br/&gt;Note that every web form resource is automatically removed from the finAPI system after 7 days from its creation.

  ## Parameters

  - connection (FinAPIAccess.Connection): Connection to server
  - id (integer()): Identifier of web form
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %FinAPIAccess.Model.WebForm{}} on success
  {:error, info} on failure
  """
  @spec get_web_form(Tesla.Env.client, integer(), keyword()) :: {:ok, FinAPIAccess.Model.WebForm.t} | {:error, Tesla.Env.t}
  def get_web_form(connection, id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/api/v1/webForms/#{id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%FinAPIAccess.Model.WebForm{})
  end
end
