# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.AccessToken do
  @moduledoc """
  User access token info
  """

  @derive [Poison.Encoder]
  defstruct [
    :"token_type",
    :"refresh_token",
    :"access_token",
    :"expires_in",
    :"scope"
  ]

  @type t :: %__MODULE__{
    :"token_type" => String.t,
    :"refresh_token" => String.t,
    :"access_token" => String.t,
    :"expires_in" => integer(),
    :"scope" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.AccessToken do
  def decode(value, _options) do
    value
  end
end

