# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.AccountList do
  @moduledoc """
  Container for data of multiple bank accounts
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accounts"
  ]

  @type t :: %__MODULE__{
    :"accounts" => [Account]
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.AccountList do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"accounts", :list, FinAPIAccess.Model.Account, options)
  end
end

