# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.AccountInterface do
  @moduledoc """
  Account interface details
  """

  @derive [Poison.Encoder]
  defstruct [
    :"interface",
    :"status",
    :"capabilities",
    :"lastSuccessfulUpdate",
    :"lastUpdateAttempt"
  ]

  @type t :: %__MODULE__{
    :"interface" => String.t,
    :"status" => String.t,
    :"capabilities" => [String.t],
    :"lastSuccessfulUpdate" => String.t,
    :"lastUpdateAttempt" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.AccountInterface do
  def decode(value, _options) do
    value
  end
end

