# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.AccountParams do
  @moduledoc """
  Container for an account&#39;s name, type and &#39;isNew&#39; flag&#39;.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountName",
    :"accountType",
    :"isNew"
  ]

  @type t :: %__MODULE__{
    :"accountName" => String.t,
    :"accountType" => String.t,
    :"isNew" => boolean()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.AccountParams do
  def decode(value, _options) do
    value
  end
end

