# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.Account do
  @moduledoc """
  Container for a bank account&#39;s data
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"bankConnectionId",
    :"accountName",
    :"iban",
    :"accountNumber",
    :"subAccountNumber",
    :"accountHolderName",
    :"accountHolderId",
    :"accountCurrency",
    :"accountType",
    :"balance",
    :"overdraft",
    :"overdraftLimit",
    :"availableFunds",
    :"isNew",
    :"interfaces",
    :"isSeized"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"bankConnectionId" => integer(),
    :"accountName" => String.t,
    :"iban" => String.t,
    :"accountNumber" => String.t,
    :"subAccountNumber" => String.t,
    :"accountHolderName" => String.t,
    :"accountHolderId" => String.t,
    :"accountCurrency" => String.t,
    :"accountType" => String.t,
    :"balance" => float(),
    :"overdraft" => float(),
    :"overdraftLimit" => float(),
    :"availableFunds" => float(),
    :"isNew" => boolean(),
    :"interfaces" => [AccountInterface],
    :"isSeized" => boolean()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.Account do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"interfaces", :list, FinAPIAccess.Model.AccountInterface, options)
  end
end

