# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.AccountReference do
  @moduledoc """
  Account reference data
  """

  @derive [Poison.Encoder]
  defstruct [
    :"iban"
  ]

  @type t :: %__MODULE__{
    :"iban" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.AccountReference do
  def decode(value, _options) do
    value
  end
end

