# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.AccountParams do
  @moduledoc """
  Container for an account's name, type and 'isNew' flag'.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountName",
    :"accountType",
    :"isNew"
  ]

  @type t :: %__MODULE__{
    :"accountName" => String.t | nil,
    :"accountType" => String.t | nil,
    :"isNew" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.AccountParams do
  def decode(value, _options) do
    value
  end
end

