# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.Bank do
  @moduledoc """
  Container for a bank's data
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"bic",
    :"blz",
    :"location",
    :"city",
    :"isTestBank",
    :"popularity",
    :"interfaces",
    :"bankGroup"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"name" => String.t,
    :"bic" => String.t | nil,
    :"blz" => String.t,
    :"location" => String.t | nil,
    :"city" => String.t | nil,
    :"isTestBank" => boolean(),
    :"popularity" => integer(),
    :"interfaces" => [BankInterface],
    :"bankGroup" => BankGroup | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.Bank do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"interfaces", :list, FinAPIAccess.Model.BankInterface, options)
    |> deserialize(:"bankGroup", :struct, FinAPIAccess.Model.BankGroup, options)
  end
end

