# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.BankInterface do
  @moduledoc """
  Interface used to connect to a bank
  """

  @derive [Poison.Encoder]
  defstruct [
    :"interface",
    :"tppAuthenticationGroup",
    :"loginCredentials",
    :"properties",
    :"loginHint",
    :"health",
    :"lastCommunicationAttempt",
    :"lastSuccessfulCommunication",
    :"isMoneyTransferSupported",
    :"isAisSupported"
  ]

  @type t :: %__MODULE__{
    :"interface" => String.t,
    :"tppAuthenticationGroup" => TppAuthenticationGroup,
    :"loginCredentials" => [BankInterfaceLoginField],
    :"properties" => [String.t],
    :"loginHint" => String.t,
    :"health" => integer(),
    :"lastCommunicationAttempt" => String.t,
    :"lastSuccessfulCommunication" => String.t,
    :"isMoneyTransferSupported" => boolean(),
    :"isAisSupported" => boolean()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.BankInterface do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"tppAuthenticationGroup", :struct, FinAPIAccess.Model.TppAuthenticationGroup, options)
    |> deserialize(:"loginCredentials", :list, FinAPIAccess.Model.BankInterfaceLoginField, options)
  end
end

