# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.BankConnectionList do
  @moduledoc """
  Container for data of multiple bank connections
  """

  @derive [Poison.Encoder]
  defstruct [
    :"connections"
  ]

  @type t :: %__MODULE__{
    :"connections" => [BankConnection]
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.BankConnectionList do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"connections", :list, FinAPIAccess.Model.BankConnection, options)
  end
end

