# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.CashFlow do
  @moduledoc """
  Cash flow
  """

  @derive [Poison.Encoder]
  defstruct [
    :"category",
    :"income",
    :"spending",
    :"balance",
    :"countIncomeTransactions",
    :"countSpendingTransactions",
    :"countAllTransactions"
  ]

  @type t :: %__MODULE__{
    :"category" => Category | nil,
    :"income" => float(),
    :"spending" => float(),
    :"balance" => float(),
    :"countIncomeTransactions" => integer(),
    :"countSpendingTransactions" => integer(),
    :"countAllTransactions" => integer()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.CashFlow do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"category", :struct, FinAPIAccess.Model.Category, options)
  end
end

