# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.CashFlowList do
  @moduledoc """
  Cash flows
  """

  @derive [Poison.Encoder]
  defstruct [
    :"cashFlows",
    :"totalIncome",
    :"totalSpending",
    :"totalBalance"
  ]

  @type t :: %__MODULE__{
    :"cashFlows" => [CashFlow],
    :"totalIncome" => float(),
    :"totalSpending" => float(),
    :"totalBalance" => float()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.CashFlowList do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"cashFlows", :list, FinAPIAccess.Model.CashFlow, options)
  end
end

