# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.CategoryParams do
  @moduledoc """
  Category parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"parentId"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"parentId" => integer() | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.CategoryParams do
  def decode(value, _options) do
    value
  end
end

