# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.Category do
  @moduledoc """
  Category data
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"parentId",
    :"parentName",
    :"isCustom",
    :"children"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"name" => String.t,
    :"parentId" => integer(),
    :"parentName" => String.t,
    :"isCustom" => boolean(),
    :"children" => [integer()]
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.Category do
  def decode(value, _options) do
    value
  end
end

