# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.ChangeClientCredentialsParams do
  @moduledoc """
  Parameters for changing client credentials
  """

  @derive [Poison.Encoder]
  defstruct [
    :"clientId",
    :"oldClientSecret",
    :"newClientSecret"
  ]

  @type t :: %__MODULE__{
    :"clientId" => String.t,
    :"oldClientSecret" => String.t,
    :"newClientSecret" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.ChangeClientCredentialsParams do
  def decode(value, _options) do
    value
  end
end

