# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.ClientConfigurationParams do
  @moduledoc """
  Client configuration parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"userNotificationCallbackUrl",
    :"userSynchronizationCallbackUrl",
    :"refreshTokensValidityPeriod",
    :"userAccessTokensValidityPeriod",
    :"clientAccessTokensValidityPeriod",
    :"storeSecretsAvailableInWebForm",
    :"applicationName",
    :"finTSProductRegistrationNumber",
    :"supportSubjectDefault",
    :"supportEmail"
  ]

  @type t :: %__MODULE__{
    :"userNotificationCallbackUrl" => String.t,
    :"userSynchronizationCallbackUrl" => String.t,
    :"refreshTokensValidityPeriod" => integer(),
    :"userAccessTokensValidityPeriod" => integer(),
    :"clientAccessTokensValidityPeriod" => integer(),
    :"storeSecretsAvailableInWebForm" => boolean(),
    :"applicationName" => String.t,
    :"finTSProductRegistrationNumber" => String.t,
    :"supportSubjectDefault" => String.t,
    :"supportEmail" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.ClientConfigurationParams do
  def decode(value, _options) do
    value
  end
end

