# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.ClientConfiguration do
  @moduledoc """
  Client configuration parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"isAutomaticBatchUpdateEnabled",
    :"isDevelopmentModeEnabled",
    :"isNonEuroAccountsSupported",
    :"isAutoCategorizationEnabled",
    :"mandatorLicense",
    :"preferredConsentType",
    :"userNotificationCallbackUrl",
    :"userSynchronizationCallbackUrl",
    :"refreshTokensValidityPeriod",
    :"userAccessTokensValidityPeriod",
    :"clientAccessTokensValidityPeriod",
    :"maxUserLoginAttempts",
    :"transactionImportLimitation",
    :"isUserAutoVerificationEnabled",
    :"isMandatorAdmin",
    :"isWebScrapingEnabled",
    :"isStandalonePaymentsEnabled",
    :"availableBankGroups",
    :"products",
    :"applicationName",
    :"finTSProductRegistrationNumber",
    :"storeSecretsAvailableInWebForm",
    :"supportSubjectDefault",
    :"supportEmail",
    :"aisWebFormMode",
    :"pisWebFormMode",
    :"pisStandaloneWebFormMode",
    :"paymentsEnabled"
  ]

  @type t :: %__MODULE__{
    :"isAutomaticBatchUpdateEnabled" => boolean(),
    :"isDevelopmentModeEnabled" => boolean(),
    :"isNonEuroAccountsSupported" => boolean(),
    :"isAutoCategorizationEnabled" => boolean(),
    :"mandatorLicense" => String.t,
    :"preferredConsentType" => String.t,
    :"userNotificationCallbackUrl" => String.t,
    :"userSynchronizationCallbackUrl" => String.t,
    :"refreshTokensValidityPeriod" => integer(),
    :"userAccessTokensValidityPeriod" => integer(),
    :"clientAccessTokensValidityPeriod" => integer(),
    :"maxUserLoginAttempts" => integer(),
    :"transactionImportLimitation" => integer(),
    :"isUserAutoVerificationEnabled" => boolean(),
    :"isMandatorAdmin" => boolean(),
    :"isWebScrapingEnabled" => boolean(),
    :"isStandalonePaymentsEnabled" => boolean(),
    :"availableBankGroups" => [String.t],
    :"products" => [String.t],
    :"applicationName" => String.t,
    :"finTSProductRegistrationNumber" => String.t,
    :"storeSecretsAvailableInWebForm" => boolean(),
    :"supportSubjectDefault" => String.t,
    :"supportEmail" => String.t,
    :"aisWebFormMode" => String.t,
    :"pisWebFormMode" => String.t,
    :"pisStandaloneWebFormMode" => String.t,
    :"paymentsEnabled" => boolean()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.ClientConfiguration do
  def decode(value, _options) do
    value
  end
end

