# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.CreateDirectDebitParams do
  @moduledoc """
  Container for direct debit creation parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountId",
    :"directDebitType",
    :"sequenceType",
    :"directDebits",
    :"singleBooking",
    :"executionDate"
  ]

  @type t :: %__MODULE__{
    :"accountId" => integer(),
    :"directDebitType" => String.t,
    :"sequenceType" => String.t,
    :"directDebits" => [DirectDebitOrderParams],
    :"singleBooking" => boolean(),
    :"executionDate" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.CreateDirectDebitParams do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"directDebits", :list, FinAPIAccess.Model.DirectDebitOrderParams, options)
  end
end

