# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.CreateMoneyTransferParams do
  @moduledoc """
  Container for money transfer creation parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountId",
    :"iban",
    :"moneyTransfers",
    :"executionDate",
    :"singleBooking"
  ]

  @type t :: %__MODULE__{
    :"accountId" => integer(),
    :"iban" => String.t,
    :"moneyTransfers" => [MoneyTransferOrderParams],
    :"executionDate" => String.t,
    :"singleBooking" => boolean()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.CreateMoneyTransferParams do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"moneyTransfers", :list, FinAPIAccess.Model.MoneyTransferOrderParams, options)
  end
end

