# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.CreateMoneyTransferParams do
  @moduledoc """
  Container for money transfer creation parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"singleBooking",
    :"accountId",
    :"iban",
    :"executionDate",
    :"moneyTransfers"
  ]

  @type t :: %__MODULE__{
    :"singleBooking" => boolean() | nil,
    :"accountId" => integer() | nil,
    :"iban" => String.t | nil,
    :"executionDate" => String.t | nil,
    :"moneyTransfers" => [MoneyTransferOrderParams]
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.CreateMoneyTransferParams do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"moneyTransfers", :list, FinAPIAccess.Model.MoneyTransferOrderParams, options)
  end
end

