# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.CreateDirectDebitParams do
  @moduledoc """
  Container for direct debit creation parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"singleBooking",
    :"accountId",
    :"directDebitType",
    :"sequenceType",
    :"directDebits",
    :"executionDate"
  ]

  @type t :: %__MODULE__{
    :"singleBooking" => boolean() | nil,
    :"accountId" => integer(),
    :"directDebitType" => String.t,
    :"sequenceType" => String.t,
    :"directDebits" => [DirectDebitOrderParams],
    :"executionDate" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.CreateDirectDebitParams do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"directDebits", :list, FinAPIAccess.Model.DirectDebitOrderParams, options)
  end
end

