# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.DailyBalanceList do
  @moduledoc """
  Contains a list of daily balances
  """

  @derive [Poison.Encoder]
  defstruct [
    :"latestCommonBalanceTimestamp",
    :"dailyBalances",
    :"paging"
  ]

  @type t :: %__MODULE__{
    :"latestCommonBalanceTimestamp" => String.t | nil,
    :"dailyBalances" => [DailyBalance],
    :"paging" => Paging
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.DailyBalanceList do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"dailyBalances", :list, FinAPIAccess.Model.DailyBalance, options)
    |> deserialize(:"paging", :struct, FinAPIAccess.Model.Paging, options)
  end
end

