# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.DirectDebitOrderParams do
  @moduledoc """
  Parameters for a direct debit order
  """

  @derive [Poison.Encoder]
  defstruct [
    :"counterpartName",
    :"counterpartIban",
    :"counterpartBic",
    :"amount",
    :"purpose",
    :"sepaPurposeCode",
    :"endToEndId",
    :"mandateId",
    :"mandateDate",
    :"creditorId",
    :"counterpartAddress",
    :"counterpartCountry"
  ]

  @type t :: %__MODULE__{
    :"counterpartName" => String.t,
    :"counterpartIban" => String.t,
    :"counterpartBic" => String.t,
    :"amount" => float(),
    :"purpose" => String.t,
    :"sepaPurposeCode" => String.t,
    :"endToEndId" => String.t,
    :"mandateId" => String.t,
    :"mandateDate" => String.t,
    :"creditorId" => String.t,
    :"counterpartAddress" => String.t,
    :"counterpartCountry" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.DirectDebitOrderParams do
  def decode(value, _options) do
    value
  end
end

