# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.EditBankConnectionParams do
  @moduledoc """
  Container for bank connection edit params
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"interface",
    :"loginCredentials",
    :"defaultTwoStepProcedureId"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t | nil,
    :"interface" => String.t | nil,
    :"loginCredentials" => [LoginCredential] | nil,
    :"defaultTwoStepProcedureId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.EditBankConnectionParams do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"loginCredentials", :list, FinAPIAccess.Model.LoginCredential, options)
  end
end

