# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.EditBankConnectionParams do
  @moduledoc """
  Container for bank connection edit params
  """

  @derive [Poison.Encoder]
  defstruct [
    :"name",
    :"interface",
    :"loginCredentials",
    :"defaultTwoStepProcedureId"
  ]

  @type t :: %__MODULE__{
    :"name" => String.t,
    :"interface" => String.t,
    :"loginCredentials" => [LoginCredential],
    :"defaultTwoStepProcedureId" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.EditBankConnectionParams do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"loginCredentials", :list, FinAPIAccess.Model.LoginCredential, options)
  end
end

