# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.ErrorMessage do
  @moduledoc """
  Response type when a service call was not successful. Contains details about the error(s) that occurred.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"errors",
    :"date",
    :"endpoint",
    :"authContext",
    :"bank"
  ]

  @type t :: %__MODULE__{
    :"errors" => [ErrorDetails],
    :"date" => String.t,
    :"endpoint" => String.t,
    :"authContext" => String.t,
    :"bank" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.ErrorMessage do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"errors", :list, FinAPIAccess.Model.ErrorDetails, options)
  end
end

