# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.ErrorDetails do
  @moduledoc """
  Error details
  """

  @derive [Poison.Encoder]
  defstruct [
    :"message",
    :"code",
    :"type",
    :"multiStepAuthentication"
  ]

  @type t :: %__MODULE__{
    :"message" => String.t,
    :"code" => String.t,
    :"type" => String.t,
    :"multiStepAuthentication" => MultiStepAuthenticationChallenge
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.ErrorDetails do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"multiStepAuthentication", :struct, FinAPIAccess.Model.MultiStepAuthenticationChallenge, options)
  end
end

