# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.IbanRuleParams do
  @moduledoc """
  Parameters of IBAN rule
  """

  @derive [Poison.Encoder]
  defstruct [
    :"iban",
    :"categoryId",
    :"direction"
  ]

  @type t :: %__MODULE__{
    :"iban" => String.t,
    :"categoryId" => integer(),
    :"direction" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.IbanRuleParams do
  def decode(value, _options) do
    value
  end
end

