# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.IbanRulesParams do
  @moduledoc """
  Params for creation of IBAN rules
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ibanRules"
  ]

  @type t :: %__MODULE__{
    :"ibanRules" => [IbanRuleParams]
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.IbanRulesParams do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ibanRules", :list, FinAPIAccess.Model.IbanRuleParams, options)
  end
end

