# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.ImportBankConnectionParams do
  @moduledoc """
  Container for bank connection import parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"bankId",
    :"name",
    :"interface",
    :"loginCredentials",
    :"storeSecrets",
    :"skipPositionsDownload",
    :"loadOwnerData",
    :"maxDaysForDownload",
    :"accountTypes",
    :"accountReferences",
    :"multiStepAuthentication",
    :"redirectUrl"
  ]

  @type t :: %__MODULE__{
    :"bankId" => integer(),
    :"name" => String.t,
    :"interface" => String.t,
    :"loginCredentials" => [LoginCredential],
    :"storeSecrets" => boolean(),
    :"skipPositionsDownload" => boolean(),
    :"loadOwnerData" => boolean(),
    :"maxDaysForDownload" => integer(),
    :"accountTypes" => [String.t],
    :"accountReferences" => [AccountReference],
    :"multiStepAuthentication" => MultiStepAuthenticationCallback,
    :"redirectUrl" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.ImportBankConnectionParams do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"loginCredentials", :list, FinAPIAccess.Model.LoginCredential, options)
    |> deserialize(:"accountReferences", :list, FinAPIAccess.Model.AccountReference, options)
    |> deserialize(:"multiStepAuthentication", :struct, FinAPIAccess.Model.MultiStepAuthenticationCallback, options)
  end
end

