# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.KeywordRuleList do
  @moduledoc """
  Container for keyword rules
  """

  @derive [Poison.Encoder]
  defstruct [
    :"keywordRules"
  ]

  @type t :: %__MODULE__{
    :"keywordRules" => [KeywordRule]
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.KeywordRuleList do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"keywordRules", :list, FinAPIAccess.Model.KeywordRule, options)
  end
end

