# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.KeywordRuleParams do
  @moduledoc """
  Parameters of keyword rule
  """

  @derive [Poison.Encoder]
  defstruct [
    :"categoryId",
    :"direction",
    :"keywords",
    :"allKeywordsMustMatch"
  ]

  @type t :: %__MODULE__{
    :"categoryId" => integer(),
    :"direction" => String.t,
    :"keywords" => [String.t],
    :"allKeywordsMustMatch" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.KeywordRuleParams do
  def decode(value, _options) do
    value
  end
end

