# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.KeywordRule do
  @moduledoc """
  Container for a keyword rule
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"category",
    :"direction",
    :"creationDate",
    :"keywords",
    :"allKeywordsMustMatch"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"category" => Category,
    :"direction" => String.t,
    :"creationDate" => String.t,
    :"keywords" => [String.t],
    :"allKeywordsMustMatch" => boolean()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.KeywordRule do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"category", :struct, FinAPIAccess.Model.Category, options)
  end
end

