# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.MockBatchUpdateParams do
  @moduledoc """
  Data for mock bank connection updates
  """

  @derive [Poison.Encoder]
  defstruct [
    :"mockBankConnectionUpdates",
    :"triggerNotifications"
  ]

  @type t :: %__MODULE__{
    :"mockBankConnectionUpdates" => [MockBankConnectionUpdate],
    :"triggerNotifications" => boolean()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.MockBatchUpdateParams do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"mockBankConnectionUpdates", :list, FinAPIAccess.Model.MockBankConnectionUpdate, options)
  end
end

