# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.MockAccountData do
  @moduledoc """
  Mock account data
  """

  @derive [Poison.Encoder]
  defstruct [
    :"accountId",
    :"accountBalance",
    :"newTransactions"
  ]

  @type t :: %__MODULE__{
    :"accountId" => integer(),
    :"accountBalance" => float(),
    :"newTransactions" => [NewTransaction] | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.MockAccountData do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"newTransactions", :list, FinAPIAccess.Model.NewTransaction, options)
  end
end

