# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.MoneyTransferOrderParams do
  @moduledoc """
  Parameters for a money transfer order
  """

  @derive [Poison.Encoder]
  defstruct [
    :"counterpartName",
    :"counterpartIban",
    :"counterpartBic",
    :"amount",
    :"purpose",
    :"sepaPurposeCode",
    :"endToEndId"
  ]

  @type t :: %__MODULE__{
    :"counterpartName" => String.t,
    :"counterpartIban" => String.t,
    :"counterpartBic" => String.t | nil,
    :"amount" => float(),
    :"purpose" => String.t | nil,
    :"sepaPurposeCode" => String.t | nil,
    :"endToEndId" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.MoneyTransferOrderParams do
  def decode(value, _options) do
    value
  end
end

