# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.MultiStepAuthenticationCallback do
  @moduledoc """
  Container for multi-step authentication data, as passed by the client to finAPI
  """

  @derive [Poison.Encoder]
  defstruct [
    :"hash",
    :"challengeResponse",
    :"twoStepProcedureId",
    :"redirectCallback",
    :"decoupledCallback"
  ]

  @type t :: %__MODULE__{
    :"hash" => String.t,
    :"challengeResponse" => String.t,
    :"twoStepProcedureId" => String.t,
    :"redirectCallback" => String.t,
    :"decoupledCallback" => boolean()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.MultiStepAuthenticationCallback do
  def decode(value, _options) do
    value
  end
end

