# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.MultiStepAuthenticationChallenge do
  @moduledoc """
  Container for multi-step authentication data, as returned by finAPI to the client
  """

  @derive [Poison.Encoder]
  defstruct [
    :"hash",
    :"status",
    :"challengeMessage",
    :"answerFieldLabel",
    :"redirectUrl",
    :"redirectContext",
    :"redirectContextField",
    :"twoStepProcedures",
    :"photoTanMimeType",
    :"photoTanData",
    :"opticalData"
  ]

  @type t :: %__MODULE__{
    :"hash" => String.t,
    :"status" => String.t,
    :"challengeMessage" => String.t | nil,
    :"answerFieldLabel" => String.t | nil,
    :"redirectUrl" => String.t | nil,
    :"redirectContext" => String.t | nil,
    :"redirectContextField" => String.t | nil,
    :"twoStepProcedures" => [TwoStepProcedure] | nil,
    :"photoTanMimeType" => String.t | nil,
    :"photoTanData" => String.t | nil,
    :"opticalData" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.MultiStepAuthenticationChallenge do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"twoStepProcedures", :list, FinAPIAccess.Model.TwoStepProcedure, options)
  end
end

