# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.NewTransaction do
  @moduledoc """
  Mock transaction data
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amount",
    :"purpose",
    :"counterpart",
    :"counterpartIban",
    :"counterpartBlz",
    :"counterpartBic",
    :"counterpartAccountNumber",
    :"bookingDate",
    :"valueDate",
    :"typeId",
    :"counterpartMandateReference",
    :"counterpartCreditorId",
    :"counterpartCustomerReference",
    :"counterpartDebitorId",
    :"type",
    :"typeCodeSwift"
  ]

  @type t :: %__MODULE__{
    :"amount" => float(),
    :"purpose" => String.t | nil,
    :"counterpart" => String.t | nil,
    :"counterpartIban" => String.t | nil,
    :"counterpartBlz" => String.t | nil,
    :"counterpartBic" => String.t | nil,
    :"counterpartAccountNumber" => String.t | nil,
    :"bookingDate" => String.t | nil,
    :"valueDate" => String.t | nil,
    :"typeId" => integer() | nil,
    :"counterpartMandateReference" => String.t | nil,
    :"counterpartCreditorId" => String.t | nil,
    :"counterpartCustomerReference" => String.t | nil,
    :"counterpartDebitorId" => String.t | nil,
    :"type" => String.t | nil,
    :"typeCodeSwift" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.NewTransaction do
  def decode(value, _options) do
    value
  end
end

