# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.NewTransaction do
  @moduledoc """
  Mock transaction data
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amount",
    :"purpose",
    :"counterpart",
    :"counterpartIban",
    :"counterpartBlz",
    :"counterpartBic",
    :"counterpartAccountNumber",
    :"bookingDate",
    :"valueDate",
    :"typeId",
    :"counterpartMandateReference",
    :"counterpartCreditorId",
    :"counterpartCustomerReference",
    :"counterpartDebitorId",
    :"type",
    :"typeCodeSwift"
  ]

  @type t :: %__MODULE__{
    :"amount" => float(),
    :"purpose" => String.t,
    :"counterpart" => String.t,
    :"counterpartIban" => String.t,
    :"counterpartBlz" => String.t,
    :"counterpartBic" => String.t,
    :"counterpartAccountNumber" => String.t,
    :"bookingDate" => String.t,
    :"valueDate" => String.t,
    :"typeId" => integer(),
    :"counterpartMandateReference" => String.t,
    :"counterpartCreditorId" => String.t,
    :"counterpartCustomerReference" => String.t,
    :"counterpartDebitorId" => String.t,
    :"type" => String.t,
    :"typeCodeSwift" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.NewTransaction do
  def decode(value, _options) do
    value
  end
end

