# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.NotificationRuleParams do
  @moduledoc """
  Parameters of notification rule
  """

  @derive [Poison.Encoder]
  defstruct [
    :"triggerEvent",
    :"params",
    :"callbackHandle",
    :"includeDetails"
  ]

  @type t :: %__MODULE__{
    :"triggerEvent" => String.t,
    :"params" => %{optional(String.t) => String.t} | nil,
    :"callbackHandle" => String.t | nil,
    :"includeDetails" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.NotificationRuleParams do
  def decode(value, _options) do
    value
  end
end

