# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.PageableTppCertificateList do
  @moduledoc """
  Container for bank certificate information with paging info
  """

  @derive [Poison.Encoder]
  defstruct [
    :"tppCertificates",
    :"paging"
  ]

  @type t :: %__MODULE__{
    :"tppCertificates" => [TppCertificate],
    :"paging" => Paging
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.PageableTppCertificateList do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"tppCertificates", :list, FinAPIAccess.Model.TppCertificate, options)
    |> deserialize(:"paging", :struct, FinAPIAccess.Model.Paging, options)
  end
end

