# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.PageableKeywordRuleList do
  @moduledoc """
  Container for keyword rule information with paging info
  """

  @derive [Poison.Encoder]
  defstruct [
    :"keywordRules",
    :"paging"
  ]

  @type t :: %__MODULE__{
    :"keywordRules" => [KeywordRule],
    :"paging" => Paging
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.PageableKeywordRuleList do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"keywordRules", :list, FinAPIAccess.Model.KeywordRule, options)
    |> deserialize(:"paging", :struct, FinAPIAccess.Model.Paging, options)
  end
end

