# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.PageableTransactionList do
  @moduledoc """
  Container for a page of transactions, with data about the total count of transactions and their balance with paging information
  """

  @derive [Poison.Encoder]
  defstruct [
    :"transactions",
    :"paging",
    :"income",
    :"spending",
    :"balance"
  ]

  @type t :: %__MODULE__{
    :"transactions" => [Transaction],
    :"paging" => Paging,
    :"income" => float(),
    :"spending" => float(),
    :"balance" => float()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.PageableTransactionList do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"transactions", :list, FinAPIAccess.Model.Transaction, options)
    |> deserialize(:"paging", :struct, FinAPIAccess.Model.Paging, options)
  end
end

