# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.PageableBankList do
  @moduledoc """
  Container for banks with paging information
  """

  @derive [Poison.Encoder]
  defstruct [
    :"banks",
    :"paging"
  ]

  @type t :: %__MODULE__{
    :"banks" => [Bank],
    :"paging" => Paging
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.PageableBankList do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"banks", :list, FinAPIAccess.Model.Bank, options)
    |> deserialize(:"paging", :struct, FinAPIAccess.Model.Paging, options)
  end
end

