# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.PageableTppCredentialResources do
  @moduledoc """
  Container for TPP client credentials information with paging info
  """

  @derive [Poison.Encoder]
  defstruct [
    :"tppCredentials",
    :"paging"
  ]

  @type t :: %__MODULE__{
    :"tppCredentials" => [TppCredentials],
    :"paging" => Paging
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.PageableTppCredentialResources do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"tppCredentials", :list, FinAPIAccess.Model.TppCredentials, options)
    |> deserialize(:"paging", :struct, FinAPIAccess.Model.Paging, options)
  end
end

