# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.PageableCategoryList do
  @moduledoc """
  Container for categories with paging information
  """

  @derive [Poison.Encoder]
  defstruct [
    :"categories",
    :"paging"
  ]

  @type t :: %__MODULE__{
    :"categories" => [Category],
    :"paging" => Paging
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.PageableCategoryList do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"categories", :list, FinAPIAccess.Model.Category, options)
    |> deserialize(:"paging", :struct, FinAPIAccess.Model.Paging, options)
  end
end

