# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.PageableLabelList do
  @moduledoc """
  Label resources with paging information
  """

  @derive [Poison.Encoder]
  defstruct [
    :"labels",
    :"paging"
  ]

  @type t :: %__MODULE__{
    :"labels" => [Label],
    :"paging" => Paging
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.PageableLabelList do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"labels", :list, FinAPIAccess.Model.Label, options)
    |> deserialize(:"paging", :struct, FinAPIAccess.Model.Paging, options)
  end
end

