# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.PageableBankList do
  @moduledoc """
  Container for banks with paging info
  """

  @derive [Poison.Encoder]
  defstruct [
    :"banks",
    :"paging"
  ]

  @type t :: %__MODULE__{
    :"banks" => [Bank],
    :"paging" => Paging
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.PageableBankList do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"banks", :list, FinAPIAccess.Model.Bank, options)
    |> deserialize(:"paging", :struct, FinAPIAccess.Model.Paging, options)
  end
end

