# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.PageablePaymentResources do
  @moduledoc """
  Payment resources with paging information
  """

  @derive [Poison.Encoder]
  defstruct [
    :"payments",
    :"paging"
  ]

  @type t :: %__MODULE__{
    :"payments" => [Payment],
    :"paging" => Paging
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.PageablePaymentResources do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"payments", :list, FinAPIAccess.Model.Payment, options)
    |> deserialize(:"paging", :struct, FinAPIAccess.Model.Paging, options)
  end
end

