# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.PageableIbanRuleList do
  @moduledoc """
  Container for IBAN rule information with paging information
  """

  @derive [Poison.Encoder]
  defstruct [
    :"ibanRules",
    :"paging"
  ]

  @type t :: %__MODULE__{
    :"ibanRules" => [IbanRule],
    :"paging" => Paging
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.PageableIbanRuleList do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"ibanRules", :list, FinAPIAccess.Model.IbanRule, options)
    |> deserialize(:"paging", :struct, FinAPIAccess.Model.Paging, options)
  end
end

