# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.RemoveInterfaceParams do
  @moduledoc """
  Container for interface removal parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"bankConnectionId",
    :"interface"
  ]

  @type t :: %__MODULE__{
    :"bankConnectionId" => integer(),
    :"interface" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.RemoveInterfaceParams do
  def decode(value, _options) do
    value
  end
end

