# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.RequestPasswordChangeParams do
  @moduledoc """
  Request password change parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"userId"
  ]

  @type t :: %__MODULE__{
    :"userId" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.RequestPasswordChangeParams do
  def decode(value, _options) do
    value
  end
end

