# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.Security do
  @moduledoc """
  Container for a security position&#39;s data
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"accountId",
    :"name",
    :"isin",
    :"wkn",
    :"quote",
    :"quoteCurrency",
    :"quoteType",
    :"quoteDate",
    :"quantityNominal",
    :"quantityNominalType",
    :"marketValue",
    :"marketValueCurrency",
    :"entryQuote",
    :"entryQuoteCurrency",
    :"profitOrLoss"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"accountId" => integer(),
    :"name" => String.t,
    :"isin" => String.t,
    :"wkn" => String.t,
    :"quote" => float(),
    :"quoteCurrency" => String.t,
    :"quoteType" => String.t,
    :"quoteDate" => String.t,
    :"quantityNominal" => float(),
    :"quantityNominalType" => String.t,
    :"marketValue" => float(),
    :"marketValueCurrency" => String.t,
    :"entryQuote" => float(),
    :"entryQuoteCurrency" => String.t,
    :"profitOrLoss" => float()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.Security do
  def decode(value, _options) do
    value
  end
end

