# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.SplitTransactionsParams do
  @moduledoc """
  Set of logical sub-transactions that a transaction should get split into
  """

  @derive [Poison.Encoder]
  defstruct [
    :"subTransactions"
  ]

  @type t :: %__MODULE__{
    :"subTransactions" => [SubTransactionParams]
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.SplitTransactionsParams do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"subTransactions", :list, FinAPIAccess.Model.SubTransactionParams, options)
  end
end

