# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.SubTransactionParams do
  @moduledoc """
  Data of a sub-transaction
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amount",
    :"categoryId",
    :"purpose",
    :"counterpart",
    :"counterpartAccountNumber",
    :"counterpartIban",
    :"counterpartBic",
    :"counterpartBlz",
    :"labelIds"
  ]

  @type t :: %__MODULE__{
    :"amount" => float(),
    :"categoryId" => integer(),
    :"purpose" => String.t,
    :"counterpart" => String.t,
    :"counterpartAccountNumber" => String.t,
    :"counterpartIban" => String.t,
    :"counterpartBic" => String.t,
    :"counterpartBlz" => String.t,
    :"labelIds" => [integer()]
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.SubTransactionParams do
  def decode(value, _options) do
    value
  end
end

