# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.SubmitPaymentParams do
  @moduledoc """
  Payment submission parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"paymentId",
    :"interface",
    :"loginCredentials",
    :"redirectUrl",
    :"multiStepAuthentication",
    :"hideTransactionDetailsInWebForm",
    :"forceWebForm"
  ]

  @type t :: %__MODULE__{
    :"paymentId" => integer(),
    :"interface" => String.t,
    :"loginCredentials" => [LoginCredential],
    :"redirectUrl" => String.t,
    :"multiStepAuthentication" => MultiStepAuthenticationCallback,
    :"hideTransactionDetailsInWebForm" => boolean(),
    :"forceWebForm" => boolean()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.SubmitPaymentParams do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"loginCredentials", :list, FinAPIAccess.Model.LoginCredential, options)
    |> deserialize(:"multiStepAuthentication", :struct, FinAPIAccess.Model.MultiStepAuthenticationCallback, options)
  end
end

