# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.TppCertificate do
  @moduledoc """
  A container for the bank certificate's data
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"certificateType",
    :"label",
    :"validFrom",
    :"validUntil"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"certificateType" => String.t,
    :"label" => String.t,
    :"validFrom" => String.t | nil,
    :"validUntil" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.TppCertificate do
  def decode(value, _options) do
    value
  end
end

