# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.TppCertificateParams do
  @moduledoc """
  A container for the new certificate data
  """

  @derive [Poison.Encoder]
  defstruct [
    :"type",
    :"publicKey",
    :"privateKey",
    :"passphrase",
    :"label",
    :"validFromDate",
    :"validUntilDate"
  ]

  @type t :: %__MODULE__{
    :"type" => String.t,
    :"publicKey" => String.t,
    :"privateKey" => String.t,
    :"passphrase" => String.t | nil,
    :"label" => String.t,
    :"validFromDate" => String.t | nil,
    :"validUntilDate" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.TppCertificateParams do
  def decode(value, _options) do
    value
  end
end

