# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.TppCertificate do
  @moduledoc """
  A container for the bank certificate&#39;s data
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"certificateType",
    :"label",
    :"validFrom",
    :"validUntil"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"certificateType" => String.t,
    :"label" => String.t,
    :"validFrom" => String.t,
    :"validUntil" => String.t
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.TppCertificate do
  def decode(value, _options) do
    value
  end
end

