# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.TppAuthenticationGroup do
  @moduledoc """
  TPP authentication group represents certain bank group and contains a set of TPP credentials which can be used with bank interface connected to this group.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"name" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.TppAuthenticationGroup do
  def decode(value, _options) do
    value
  end
end

