# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.TppCredentials do
  @moduledoc """
  A container for the TPP client credentials data
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"label",
    :"tppAuthenticationGroupId",
    :"validFrom",
    :"validUntil"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"label" => String.t,
    :"tppAuthenticationGroupId" => integer(),
    :"validFrom" => String.t | nil,
    :"validUntil" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.TppCredentials do
  def decode(value, _options) do
    value
  end
end

