# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.TrainCategorizationData do
  @moduledoc """
  Sample data to train categorization
  """

  @derive [Poison.Encoder]
  defstruct [
    :"transactionData",
    :"categoryId"
  ]

  @type t :: %__MODULE__{
    :"transactionData" => [TrainCategorizationTransactionData],
    :"categoryId" => integer()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.TrainCategorizationData do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"transactionData", :list, FinAPIAccess.Model.TrainCategorizationTransactionData, options)
  end
end

