# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.TriggerCategorizationParams do
  @moduledoc """
  Trigger categorization parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"bankConnectionIds"
  ]

  @type t :: %__MODULE__{
    :"bankConnectionIds" => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.TriggerCategorizationParams do
  def decode(value, _options) do
    value
  end
end

