# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.TriggerCategorizationParams do
  @moduledoc """
  Trigger categorization parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"bankConnectionIds"
  ]

  @type t :: %__MODULE__{
    :"bankConnectionIds" => [integer()]
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.TriggerCategorizationParams do
  def decode(value, _options) do
    value
  end
end

