# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.TwoStepProcedure do
  @moduledoc """
  Two-step-procedure for user authorization on bank-side
  """

  @derive [Poison.Encoder]
  defstruct [
    :"procedureId",
    :"procedureName",
    :"procedureChallengeType",
    :"implicitExecute"
  ]

  @type t :: %__MODULE__{
    :"procedureId" => String.t,
    :"procedureName" => String.t,
    :"procedureChallengeType" => String.t,
    :"implicitExecute" => boolean()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.TwoStepProcedure do
  def decode(value, _options) do
    value
  end
end

