# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.UpdateBankConnectionParams do
  @moduledoc """
  Container for bank connection update parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"bankConnectionId",
    :"interface",
    :"loginCredentials",
    :"storeSecrets",
    :"importNewAccounts",
    :"skipPositionsDownload",
    :"loadOwnerData",
    :"accountReferences",
    :"redirectUrl",
    :"forceWebForm",
    :"multiStepAuthentication"
  ]

  @type t :: %__MODULE__{
    :"bankConnectionId" => integer(),
    :"interface" => String.t | nil,
    :"loginCredentials" => [LoginCredential] | nil,
    :"storeSecrets" => boolean() | nil,
    :"importNewAccounts" => boolean() | nil,
    :"skipPositionsDownload" => boolean() | nil,
    :"loadOwnerData" => boolean() | nil,
    :"accountReferences" => [AccountReference] | nil,
    :"redirectUrl" => String.t | nil,
    :"forceWebForm" => boolean() | nil,
    :"multiStepAuthentication" => MultiStepAuthenticationCallback | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.UpdateBankConnectionParams do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"loginCredentials", :list, FinAPIAccess.Model.LoginCredential, options)
    |> deserialize(:"accountReferences", :list, FinAPIAccess.Model.AccountReference, options)
    |> deserialize(:"multiStepAuthentication", :struct, FinAPIAccess.Model.MultiStepAuthenticationCallback, options)
  end
end

