# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.UpdateMultipleTransactionsParams do
  @moduledoc """
  Update specific transactions parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"isNew",
    :"isPotentialDuplicate",
    :"categoryId",
    :"trainCategorization",
    :"labelIds",
    :"ids",
    :"accountIds"
  ]

  @type t :: %__MODULE__{
    :"isNew" => boolean(),
    :"isPotentialDuplicate" => boolean(),
    :"categoryId" => integer(),
    :"trainCategorization" => boolean(),
    :"labelIds" => [integer()],
    :"ids" => [integer()],
    :"accountIds" => [integer()]
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.UpdateMultipleTransactionsParams do
  def decode(value, _options) do
    value
  end
end

