# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.UpdateMultipleTransactionsParams do
  @moduledoc """
  Update specific transactions parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :"isNew",
    :"isPotentialDuplicate",
    :"categoryId",
    :"trainCategorization",
    :"labelIds",
    :"ids",
    :"accountIds"
  ]

  @type t :: %__MODULE__{
    :"isNew" => boolean() | nil,
    :"isPotentialDuplicate" => boolean() | nil,
    :"categoryId" => integer() | nil,
    :"trainCategorization" => boolean() | nil,
    :"labelIds" => [integer()] | nil,
    :"ids" => [integer()] | nil,
    :"accountIds" => [integer()] | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.UpdateMultipleTransactionsParams do
  def decode(value, _options) do
    value
  end
end

