# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.UserUpdateParams do
  @moduledoc """
  User details
  """

  @derive [Poison.Encoder]
  defstruct [
    :"email",
    :"phone",
    :"isAutoUpdateEnabled"
  ]

  @type t :: %__MODULE__{
    :"email" => String.t | nil,
    :"phone" => String.t | nil,
    :"isAutoUpdateEnabled" => boolean() | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.UserUpdateParams do
  def decode(value, _options) do
    value
  end
end

