# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.UserInfo do
  @moduledoc """
  Container for user information
  """

  @derive [Poison.Encoder]
  defstruct [
    :"userId",
    :"registrationDate",
    :"deletionDate",
    :"lastActiveDate",
    :"bankConnectionCount",
    :"latestBankConnectionImportDate",
    :"latestBankConnectionDeletionDate",
    :"monthlyStats",
    :"isLocked"
  ]

  @type t :: %__MODULE__{
    :"userId" => String.t,
    :"registrationDate" => String.t,
    :"deletionDate" => String.t,
    :"lastActiveDate" => String.t,
    :"bankConnectionCount" => integer(),
    :"latestBankConnectionImportDate" => String.t,
    :"latestBankConnectionDeletionDate" => String.t,
    :"monthlyStats" => [MonthlyUserStats],
    :"isLocked" => boolean()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.UserInfo do
  import FinAPIAccess.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"monthlyStats", :list, FinAPIAccess.Model.MonthlyUserStats, options)
  end
end

