# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.UserIdentifiersParams do
  @moduledoc """
  User identifiers params
  """

  @derive [Poison.Encoder]
  defstruct [
    :"userIds"
  ]

  @type t :: %__MODULE__{
    :"userIds" => [String.t]
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.UserIdentifiersParams do
  def decode(value, _options) do
    value
  end
end

