# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.VerificationStatusResource do
  @moduledoc """
  User's verification status
  """

  @derive [Poison.Encoder]
  defstruct [
    :"userId",
    :"isUserVerified"
  ]

  @type t :: %__MODULE__{
    :"userId" => String.t,
    :"isUserVerified" => boolean()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.VerificationStatusResource do
  def decode(value, _options) do
    value
  end
end

