# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule FinAPIAccess.Model.VerificationStatusResource do
  @moduledoc """
  User&#39;s verification status
  """

  @derive [Poison.Encoder]
  defstruct [
    :"userId",
    :"isUserVerified"
  ]

  @type t :: %__MODULE__{
    :"userId" => String.t,
    :"isUserVerified" => boolean()
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.VerificationStatusResource do
  def decode(value, _options) do
    value
  end
end

