# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule FinAPIAccess.Model.WebForm do
  @moduledoc """
  Container for a web form's data
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"token",
    :"status",
    :"serviceResponseCode",
    :"serviceResponseBody"
  ]

  @type t :: %__MODULE__{
    :"id" => integer(),
    :"token" => String.t,
    :"status" => String.t,
    :"serviceResponseCode" => integer() | nil,
    :"serviceResponseBody" => String.t | nil
  }
end

defimpl Poison.Decoder, for: FinAPIAccess.Model.WebForm do
  def decode(value, _options) do
    value
  end
end

